### PR TITLE
Using Baseschema as accepted schema type in options

### PR DESCRIPTION
**Pull request by ciscoheat**
According to discussion in #6. 

Also had to modify the some isoTimestamp tests to make all tests pass. Apparently, the format must be `.nnnZ` at the end.

### CODE REVIEW

**Comment by ciscoheat** [comment]
I removed the test fix, it's not relevant to this PR. Was fixed with the latest main version.

**Comment by gcornut** [comment]
Can you clean up all those commit ? 8 commit for a simple type change seems a lot. Also there is code from #10

**Comment by ciscoheat** [comment]
It was messy with merging, I might as well start over.

**Comment by ciscoheat** [comment]
Use #12 instead.

**Pull request closed without merging**
