### PR TITLE
Migrate to v0.31.0-rc5

### PR DESCRIPTION
**Pull request by slowsage**
Followed [this guide](https://valibot.dev/guides/migrate-from-v0.30.0/) using the [codemod](https://codemod.com/registry/valibot-0-30-0).
All unit tests pass.

### CODE REVIEW

**Comment by gcornut** [comment]
Thanks ! I'll give it a look this week

**Comment by slowsage** [comment]
Feel free to make changes as appropriate to this PR since it will likely need a new version number as it will be a breaking change. I have allowed edits by maintainers. Thank you!

`git clone -b valibot-v31 git@github.com:slowsage/valibot-json-schema.git`

**Comment by gcornut** [comment]
Only had to do small changes
- TS type fix on utils/valibot isSchema
- Reduced repetition on object schema conversion
- Added some test case

Thanks again for this. I'll merge this and publish a RC version on NPM

**Comment by gcornut** [comment]
Actually I already have automatic snapshot build on each push to master so I probably won't create an RC

This code is available in ~`@gcornut/valibot-json-schema@v0.30.0-snapshot.0`~ and up
Edit: sorry it's `@gcornut/valibot-json-schema@v0.0.30-snapshot.0` and up

**Comment by slowsage** [comment]
The snapshot version is set to `0.0.30` not `0.30.0`. Breaks >=.
Edit: Never mind. 0.0.30 is consistent with the prior versions.

**Pull request merged**
