### PR TITLE
Support for custom and forward function.

### PR DESCRIPTION
**Pull request by ciscoheat**
A small fix for supporting custom schemas, just a passthrough since they cannot be transformed to JSON schema.

### CODE REVIEW

**Comment by gcornut** [comment]
I'm thinking it might be better to add an option to ignore unsupported valibot validations. Some user might try to convert to JSON schema without even thinking of the fact they have custom validation that can't be converted.

**Comment by ciscoheat** [comment]
Sounds good, should I add an option like that for only custom validations, or more general?

**Comment by gcornut** [comment]
I'd say an option to ignore all unknown validations (like `ignoreUnknownValidation?: boolean`).
That way it could be changed later with an array of string to specifically list the validations to ignore but I don't know if it is useful

**Comment by ciscoheat** [comment]
Updated with that option now!

**Review by gcornut — APPROVED** [review]

**Pull request merged**
